### ISSUE TITLE
Risk Zone Issues

### ISSUE THREAD

**Issue by trickmaulz** [Palidino/BattleScape-Server#21]
Risk Zone - rejuvenation/altar of occult doesn't work
Both players should get skulled in risk-zone, only 1 does

If you freeze a person and leave the door, the person stays frozen inside the arena, which allows for you to repeat that and spec them out. Also, if you get frozen at the door then leave, you still can't move

Cannot attack players in center of risk zone

**Comment by Palidino** [comment]
Don't understand this one
Cannot attack players in center of risk zone

**Comment by Palidino** [comment]
Fixed
