### ISSUE TITLE
Ags issue

### ISSUE THREAD

**Issue by trickmaulz** [Palidino/BattleScape-Server#22]
ags is pretty inaccurate and commonly hits 0's. ags feels out classed compared to claws and vls.

**Comment by Palidino** [comment]
As discussed previously, given that the issue is with wanting the AGS to hit higher more often and not the actual accuracy being an issue (accuracy causing 0s, not low hits), I'm not sure how to proceed with this.

**Comment by trickmaulz** [comment]
@Palidino just going to close this for now unless we have other issues in the future, then we can look further into it.
