### ISSUE TITLE
[Priority] Ancient Mace

### ISSUE THREAD

**Issue by trickmaulz** [Palidino/BattleScape-Server#24]
ancient mace spec is so inaccurate its absolutely useless to use in multi.it would be fun to see the mace actually viable and have clans coordinating to try and smite skulled pvpers in multi

**Comment by Palidino** [comment]
I was actually considering removing it. When I had the pures clans join for that short time a handful of months ago, they all generally seemed to hate the mace and even had me disable it in the 1 defence wilderness instance.

**Comment by trickmaulz** [comment]
@Palidino Ancient mace is important for main clanning, I highly recommend keeping it in the game with it's full effects.

**Comment by Palidino** [comment]
I can keep it added but
"The ancient mace has stats in between those of a black mace and mithril mace"
it's really not supposed to be accurate.
