### ISSUE TITLE
Enchanted Bolt Specials

### ISSUE THREAD

**Issue by trickmaulz** [Palidino/BattleScape-Server#26]
The enchanted specials on bolts needs a buff you see it once every 3 fights max.

**Comment by Palidino** [comment]
They use the OSRS rates.
I can double check and see if they use the rates post OSRS diaries, though that'll only be a small bump.

**Comment by trickmaulz** [comment]
@Palidino yeah, double check just incase

**Comment by Palidino** [comment]
Raised.
