### ISSUE TITLE
[Important] Wilderness Line

### ISSUE THREAD

**Issue by trickmaulz** [Palidino/BattleScape-Server#35]
Remove how far in you can go before entering wilderness, make it like OSRS - also add a wilderness ditch

**Comment by Palidino** [comment]
I can re-add the wilderness line but I'm pretty sure the ditch is generally hated. The y-coordinate that the wilderness starts at is the same as OSRS already.

**Comment by trickmaulz** [comment]
@Palidino Better to add it in, because currently you can go deep into level 1 and not be in wilderness still which is quite dumb especially on a pk server

**Comment by Palidino** [comment]
Adding the ditch wouldn't fix that issue, the wilderness line is currently set to where it is on OSRS which is only a few tiles past the ditch.

**Comment by Palidino** [comment]
Which PK servers don't have to ditch to compare the starting point with BS?

**Comment by trickmaulz** [comment]
Dawntained doesn't have ditch as far as I'm aware. Not too sure about many other servers @Palidino

**Comment by Palidino** [comment]
Fixed
