### ISSUE TITLE
[Priority] Alching spawned items

### ISSUE THREAD

**Issue by trickmaulz** [Palidino/BattleScape-Server#36]
Make sure to disable alching spawned items

**Comment by trickmaulz** [comment]
@Palidino - also cannot add labels anymore

**Comment by Palidino** [comment]
Can't alch, sell to a general store, or put on the grand exchange. Also don't count toward your risked value (items on death risked value for example). Also on death, only stackables, food, and potions drop to the ground if it's a free item to minimize ground item clutter.
