### ISSUE TITLE
[Priority] Wilderness Tormented Demons

### ISSUE THREAD

**Issue by trickmaulz** [Palidino/BattleScape-Server#5]
not impossible to get item drops like ags/claws (TDS in wildy to raise activity)

**Comment by Palidino** [comment]
Wilderness tormented demons could be given dragon claw drops.

**Comment by trickmaulz** [comment]
Yeah, that's what I was suggesting @Palidino

**Comment by Palidino** [comment]
Whoops mean demonic gorillas lol, anyway added
