### ISSUE TITLE
[BUGS] Small Beta List V2

### ISSUE THREAD

**Issue by trickmaulz** [Palidino/BattleScape-Server#52]
**_Guides_**
Option 3 "Store and Bonds" hangs, potentially just because store isn't set up.
Options 4-7 open the options below, example Option 4: "Rules" options Option 6: "Shops"
Options 8-A Do nothing.
Option C Does nothing
Option E Does nothing.

**_Bonds_**
Change bond prices to $10 (especially if 1 bond = 15M)
Total redeemed does not update
**_If you have multiple mystery boxes in inventory and spam click "spin" all mboxes disappear and you don't receive an item for the last one_**
None of the options on the bonds interface work (information/donation and so on)

**_Teleport Wizard_**
Scrolling on one page, then moving to the next page will not reset page position.
Example: Select cities
Scroll to the bottom
Select Wilderness
You will see no teleports until you scroll back to the top.

**_Veng as Pure_**
Set stats to 94 mage 40+ defence, Cast vengeance
Change stats to pure
You get a free veng at the start of a pure fight.

**_Amulet of Avarace_**
Avarice amulet is supposed to skull the user upon equipping, it does not.

**_Inferno_**
Sacrificing a Fire Cape does not unlock the inferno

**_Slayer Tasks_**
Wilderness slayer tasks are not specific with locations
Also states to bring mysterious emblem with you to receive blood money per kill (not sure what this is for)

**Comment by Palidino** [comment]
The guide on the quest tab needs to be re-created based on BW information. Can prob wait until after release since there isn't a whole lot to explain on a spawn pk server.

Decided on $5/15M in discord chat a minute ago right?

You probably got the same stackable item twice when spinning them all.

Inferno should work, was this prior to the bug fix update?

**Comment by Palidino** [comment]
All resolved besides the guide section but that's on hold for now
