### ISSUE TITLE
Tournament System update

### ISSUE THREAD

**Issue by trickmaulz** [Palidino/BattleScape-Server#6]
Proper tournament system in place with commands to run different types e.g. ::07tourny 50m ::regtourny

**Comment by Palidino** [comment]
Selecting a custom tournament with a coin prize, entered value causes prizes to be handed out from ranks 1-4, each half the prize of the rank above it. Example: enter 8M as the prize, 1st gets 8M, 2nd gets 4M, 3rd gets 2M, and 4th gets 1M.
Selecting a custom tournament with OSGP as a prize announces the amount with the tournament.
