### ISSUE TITLE
[Priority] Random key rarity

### ISSUE THREAD

**Issue by trickmaulz** [Palidino/BattleScape-Server#9]
KEYS
bronze key - 35% chance
silver key - 20% chance
gold key - 10% chance
diamond key - 5% chance

not guaranteed to get key - x % chance to get it when u kill someone

bronze - supplies etc
silver - barrows supplies etc
gold - barrows, supplies, gwd
diamond - rares (phats), raids items, barrows, supplies, gwd

**Comment by Palidino** [comment]
Added
